const test = {
  _delegate: {
    _redirectEventId: undefined,
    apiKey: "AIzaSyA233CyPDDc7bmjmXAIgzD-DYyVVSIgjBs",
    appName: "[DEFAULT]",
    createdAt: "1701788971715",
    displayName: undefined,
    email: "juliusterrence.duff@gmail.com",
    emailVerified: false,
    isAnonymous: false,
    lastLoginAt: "1705776397787",
    phoneNumber: undefined,
    photoURL: undefined,
    providerData: [Array],
    stsTokenManager: [Object],
    tenantId: undefined,
    uid: "ZdfcCuXd5tcqZ91YDokONyPm5qB2",
  },
  birthdate: "1/12/2002",
  firstname: "Julius Terrence ",
  id: "ZdfcCuXd5tcqZ91YDokONyPm5qB2",
  lastname: "Duff",
  middlename: "Yape",
  multiFactor: { enrolledFactors: [], user: [Object] },
  school: "National Teachers College",
};
